services:
  # Backend (Node.js)
  - type: web
    name: eatoes-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://RestaurantAdminDashboard_db_user:RestaurantAdminDashboard@cluster0.lym6kdt.mongodb.net/?appName=Cluster0

  # Frontend (Vite/React)
  - type: static
    name: eatoes-admin
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://eatoesadimpage-10.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
